# Generated by Django 4.1 on 2024-02-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_buslocation_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buslocation',
            name='location',
        ),
        migrations.AddField(
            model_name='buslocation',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buslocation',
            name='lon',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
