# Generated by Django 4.1 on 2024-02-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_remove_buslocation_location_buslocation_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buslocation',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='buslocation',
            name='lon',
            field=models.FloatField(),
        ),
    ]
